from pinn_evaluation import pinn_violation_score
import pandas as pd
import numpy as np

def plateau_escape_stats(loss_history: list[float], search_start: int = 5000,
                         search_end: int = 30000, window: int = 500
                         ) -> tuple[int, float]:
    r"""
        Identifies the epoch and magnitude of the sharpest relative drop in a loss curve.

        Parameters
        ----------
        loss_history: list[float]
            The history of scalar loss values recorded across training epochs.

        search_start: int, default=5000
            The starting epoch constraint from which to begin looking for plateaus.

        search_end: int, default=30000
            The ending epoch constraint beyond which the search does not extend.

        window: int, default=500
            The rolling size of the lookback and lookahead assessment windows used to calculate mean loss steps.

        Returns
        -------
        epoch: int
             The training epoch that matches the point of the largest sustained relative drop.

        best_drop: float
            The maximum localised fractional drop magnitude observed between adjacent windows.

        Notes
        -----
        This function searches a designated segment of a training loss trajectory to detect where the model broke out
        of a performance plateau. It calculates a rolling relative drop by comparing the mean loss of a fixed window
        immediately before a point to the mean loss of an identical window after that point. A single-epoch relative drop
        is not used here because it is fooled by transient loss spikes late in training; a spike followed by a one-epoch
        recovery registers as a larger relative drop than the genuine transition this function is meant to capture.
        Comparing window-averaged means before and after a candidate point dilutes a brief spike while preserving
        a real sustained regime change. The default window = 500 was chosen empirically: smaller windows, e.g. 50,
        still misidentified spikes as the escape point on the real training data, even though they worked correctly
        on synthetic test cases with brief and isolated spikes.
    """
    best_i = None
    best_drop = -float('inf')

    losses = np.asarray(loss_history[search_start:search_end])

    for idx in range(window, len(losses) - window):
        before_level = np.mean(losses[idx - window: idx])
        after_level = np.mean(losses[idx + 1: idx + 1 + window])
        sustained_drop = (before_level - after_level) / before_level
        if sustained_drop > best_drop:
            best_drop = sustained_drop
            best_i = idx
    epoch = search_start + best_i

    return epoch, best_drop

def summarise_seed_sweep_parallel(results: list[dict], test_g_values: list[float]) -> pd.DataFrame:
    r"""
        Compiles per-run performance and physical-bounds validation statistics from a parallel seed sweep into a single
        summary table.

        Parameters
        ----------
        results: list[dict]
            The output list generated by train_seed_sweep_parallel. Each dictionary contains at least model, loss, lam,
            and seed - the keys that this function uses; cache_time and train_time are also present but not read.

        test_g_values: list[float]
            The out-of-sample values of the coupling constant used to measure the violations of the physical bounds.

        Returns
        -------
        pd.DataFrame
             A summary table that contains row evaluations for each execution task. Its columns are:
             a) lam: float. The hyperparameter for the second-order derivative smoothness penalty. If set to 0.0,
             the regularised penalty evaluation is circumvented.
             b) seed: int. The network initialisation random seed.
             c) violation_score: float. The accumulated out-of-bounds error on the out-of-sample values.
             d) final_loss: float. The scalar training loss value obtained at the last epoch.
             e) plateau_epoch: int. The epoch at which the largest sustained relative drop in the loss was detected;
             see plateau_escape_stats.
             f) plateau_drop_magnitude: float. The magnitude of that drop, as a fraction of the pre-drop loss level.
    """
    rows = []
    for r in results:
        r['model'].eval()
        plateau_epoch, plateau_magnitude = plateau_escape_stats(r['loss'])
        score = pinn_violation_score(r['model'], test_g_values)
        rows.append({'lam': r['lam'], 'seed': r['seed'], 'violation_score': score.item(),
                     'final_loss': r['loss'][-1], 'plateau_epoch': plateau_epoch,
                     'plateau_drop_magnitude': plateau_magnitude}
                    )

    return pd.DataFrame(rows)

if __name__ == "__main__":
    from training_loop import train_seed_sweep_parallel
    from ope_bounds_data import available_g_ope_values
    from pathlib import Path
    import pickle

    results = train_seed_sweep_parallel(lams=[0, 0.001, 0.01, 0.1], seeds=[0, 1, 2, 3, 4], n_epochs=30000)
    loss_histories = {(r['lam'], r['seed']): r['loss'] for r in results}
    with open(Path(__file__).parent.parent / 'models' / 'loss_histories.pkl', 'wb') as f:
        pickle.dump(loss_histories, f)

    test_g_values = available_g_ope_values[::10]
    summary = summarise_seed_sweep_parallel(results, test_g_values)
    summary.to_csv(Path(__file__).parent.parent / "models" / "summaries_seed_sweep_parallel.csv", index=False)
    print(summary)
